# Generated by Django 6.0.4 on 2026-04-08 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=300)),
                ('perspective', models.CharField(max_length=100)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startegy_objectives', to='STRATEGYMANAGEMENT.strategy')),
            ],
        ),
    ]
