# Generated by Django 6.0.4 on 2026-04-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STRATEGYMANAGEMENT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicobjective',
            name='perspective',
            field=models.CharField(blank=True, choices=[('Financial', 'Financial'), ('Customer', 'Customer'), ('Internal Process', 'Internal Process'), ('Learning & Growth', 'Learning & Growth')], max_length=100, null=True),
        ),
    ]
