# Generated by Django 6.0.4 on 2026-04-08 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ORGDATA', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.CharField(max_length=50)),
                ('daystaken', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Postal_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_town_village', models.CharField(max_length=100)),
                ('post_number', models.CharField(max_length=30)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postal_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Residential_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_village_town', models.CharField(max_length=100)),
                ('location_ward', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=100)),
                ('plot_number', models.CharField(max_length=30)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residential_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middlename', models.CharField(max_length=50, null=True)),
                ('national_ID', models.CharField(max_length=20, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('postal_address', models.CharField(max_length=50, null=True)),
                ('mobile_number', models.CharField(max_length=20, null=True)),
                ('mobile_number2', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('empcode', models.CharField(default='None', max_length=50)),
                ('offcielocation', models.CharField(default='None', max_length=100)),
                ('invoicesubmission_officer', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to='ORGDATA.job_profiles')),
                ('related_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_department', to='ORGDATA.departments')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_section', to='ORGDATA.sections')),
                ('sub_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_subsection', to='ORGDATA.subsections')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervisot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
