# Generated by Django 6.0.4 on 2026-04-08 08:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ORGDATA', '0001_initial'),
        ('STRATEGYMANAGEMENT', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('financial_year', models.CharField(max_length=20)),
                ('quarter', models.CharField(max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Risk Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RiskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_number', models.CharField(blank=True, help_text='Auto-generated if blank, e.g. "FI001"', max_length=20)),
                ('entry_type', models.CharField(choices=[('risk', 'Risk'), ('issue', 'Issue')], default='risk', max_length=10)),
                ('description', models.TextField()),
                ('contributing_factors', models.TextField(blank=True, help_text='Drivers / indicators / causes of the risk')),
                ('consequences', models.TextField(blank=True, help_text='Potential or actual consequences if the risk materializes')),
                ('speed_of_onset', models.CharField(blank=True, choices=[('instant', 'Instant'), ('rapid', 'Rapid (hours)'), ('moderate', 'Moderate (days)'), ('slow', 'Slow (weeks+)')], max_length=20)),
                ('inherent_impact', models.PositiveSmallIntegerField(choices=[(1, 'Negligible (1) - Minimal impact'), (2, 'Significant (2) - Minor impact'), (3, 'Major (3) - Notable impact'), (4, 'Critical (4) - Severe impact'), (5, 'Catastrophic (5) - Threatens business')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('inherent_likelihood', models.PositiveSmallIntegerField(choices=[(1, 'Unlikely (0-20%)'), (2, 'Occasionally (21-40%)'), (3, 'Likely (41-60%)'), (4, 'Highly Likely (61-80%)'), (5, 'Almost Certain (81-100%)'), (6, 'Occurred (Happening now)')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('existing_controls', models.TextField(blank=True)),
                ('control_effectiveness', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'None (0-19%) - No controls'), (1, 'Weak (20-39%) - Major deficiencies'), (2, 'Satisfactory (40-59%) - Needs improvement'), (3, 'Good (60-89%) - Majority controlled'), (4, 'Very Good (90-100%) - Effectively controlled')], null=True)),
                ('residual_impact', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Negligible (1) - Minimal impact'), (2, 'Significant (2) - Minor impact'), (3, 'Major (3) - Notable impact'), (4, 'Critical (4) - Severe impact'), (5, 'Catastrophic (5) - Threatens business')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('residual_likelihood', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Unlikely (0-20%)'), (2, 'Occasionally (21-40%)'), (3, 'Likely (41-60%)'), (4, 'Highly Likely (61-80%)'), (5, 'Almost Certain (81-100%)'), (6, 'Occurred (Happening now)')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('response_strategy', models.CharField(blank=True, choices=[('avoid', 'Terminate/Avoid'), ('transfer', 'Transfer/Share'), ('mitigate', 'Treat/Mitigate'), ('accept', 'Tolerate/Accept')], max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Use when an exact due date is known', null=True)),
                ('due_period', models.CharField(blank=True, help_text='Use for quarter-style values like "Q2 2025/26"', max_length=50)),
                ('risk_trend', models.CharField(blank=True, choices=[('up', 'Upward'), ('down', 'Downward'), ('steady', 'Steady/Stable')], max_length=10)),
                ('response_status', models.CharField(choices=[('open', 'Open (not started)'), ('progress', 'Open (in progress)'), ('overdue', 'Past due date'), ('completed', 'Completed'), ('closed', 'Closed')], default='open', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='RISK_REGISTER.riskcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_risk_items', to=settings.AUTH_USER_MODEL)),
                ('escalation_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalated_risks', to='ORGDATA.govbodies')),
                ('responsible', models.ForeignKey(blank=True, help_text='Operational role responsible for implementing responses/actions', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_risks', to='ORGDATA.job_title')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_user_risks', to=settings.AUTH_USER_MODEL)),
                ('risk_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_risks', to='ORGDATA.job_title')),
                ('risk_owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_user_risks', to=settings.AUTH_USER_MODEL)),
                ('strategic_objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='STRATEGYMANAGEMENT.strategicobjective')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_risk_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['register', 'risk_number'],
            },
        ),
        migrations.CreateModel(
            name='RiskActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Creation'), ('update', 'Update'), ('status', 'Status Change'), ('comment', 'Comment'), ('review', 'Review'), ('delete', 'Deletion')], max_length=20)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('comments', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_logs', to='RISK_REGISTER.riskitem')),
            ],
            options={
                'verbose_name': 'Action Log',
                'verbose_name_plural': 'Action Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RiskRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('workflow_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_registers', to='ORGDATA.departments')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_risk_registers', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_risk_registers', to=settings.AUTH_USER_MODEL)),
                ('reporting_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_registers', to='RISK_REGISTER.reportingperiod')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_risk_registers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Department__name', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='riskitem',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='RISK_REGISTER.riskregister'),
        ),
        migrations.CreateModel(
            name='RiskReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(default=django.utils.timezone.localdate)),
                ('comments', models.TextField(blank=True)),
                ('updated_inherent_impact', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Negligible (1) - Minimal impact'), (2, 'Significant (2) - Minor impact'), (3, 'Major (3) - Notable impact'), (4, 'Critical (4) - Severe impact'), (5, 'Catastrophic (5) - Threatens business')], null=True)),
                ('updated_inherent_likelihood', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Unlikely (0-20%)'), (2, 'Occasionally (21-40%)'), (3, 'Likely (41-60%)'), (4, 'Highly Likely (61-80%)'), (5, 'Almost Certain (81-100%)'), (6, 'Occurred (Happening now)')], null=True)),
                ('updated_residual_impact', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Negligible (1) - Minimal impact'), (2, 'Significant (2) - Minor impact'), (3, 'Major (3) - Notable impact'), (4, 'Critical (4) - Severe impact'), (5, 'Catastrophic (5) - Threatens business')], null=True)),
                ('updated_residual_likelihood', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Unlikely (0-20%)'), (2, 'Occasionally (21-40%)'), (3, 'Likely (41-60%)'), (4, 'Highly Likely (61-80%)'), (5, 'Almost Certain (81-100%)'), (6, 'Occurred (Happening now)')], null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_reviews', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='RISK_REGISTER.riskitem')),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='RiskMitigationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.TextField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('target_period', models.CharField(blank=True, help_text='Alternative to target_date, e.g. "Q3 2025/26"', max_length=50)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('progress_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_mitigation_actions', to=settings.AUTH_USER_MODEL)),
                ('owner_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_mitigation_actions', to='ORGDATA.job_title')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_mitigation_actions', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_actions', to='RISK_REGISTER.riskitem')),
            ],
            options={
                'ordering': ['target_date', 'id'],
                'indexes': [models.Index(fields=['status'], name='RISK_REGIST_status_52f936_idx'), models.Index(fields=['target_date'], name='RISK_REGIST_target__8c93f2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='riskregister',
            index=models.Index(fields=['workflow_status'], name='RISK_REGIST_workflo_1ec6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='riskregister',
            index=models.Index(fields=['is_active'], name='RISK_REGIST_is_acti_5c6c9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='riskregister',
            unique_together={('Department', 'reporting_period')},
        ),
        migrations.AddIndex(
            model_name='riskitem',
            index=models.Index(fields=['entry_type'], name='RISK_REGIST_entry_t_078677_idx'),
        ),
        migrations.AddIndex(
            model_name='riskitem',
            index=models.Index(fields=['response_status'], name='RISK_REGIST_respons_7f977b_idx'),
        ),
        migrations.AddIndex(
            model_name='riskitem',
            index=models.Index(fields=['category'], name='RISK_REGIST_categor_f6b37b_idx'),
        ),
        migrations.AddIndex(
            model_name='riskitem',
            index=models.Index(fields=['risk_owner'], name='RISK_REGIST_risk_ow_400c66_idx'),
        ),
        migrations.AddIndex(
            model_name='riskitem',
            index=models.Index(fields=['risk_owner_user'], name='RISK_REGIST_risk_ow_74c36c_idx'),
        ),
        migrations.AddIndex(
            model_name='riskitem',
            index=models.Index(fields=['responsible'], name='RISK_REGIST_respons_979443_idx'),
        ),
        migrations.AddIndex(
            model_name='riskitem',
            index=models.Index(fields=['responsible_user'], name='RISK_REGIST_respons_d12877_idx'),
        ),
        migrations.AddIndex(
            model_name='riskitem',
            index=models.Index(fields=['due_date'], name='RISK_REGIST_due_dat_d05b29_idx'),
        ),
        migrations.AddIndex(
            model_name='riskitem',
            index=models.Index(fields=['last_review_date'], name='RISK_REGIST_last_re_65f8d0_idx'),
        ),
        migrations.AddIndex(
            model_name='riskitem',
            index=models.Index(fields=['next_review_date'], name='RISK_REGIST_next_re_025552_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='riskitem',
            unique_together={('register', 'risk_number')},
        ),
    ]
